In [95]:
import talib 
import numpy as np
import pandas as pd 
import cufflinks as cf
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot
init_notebook_mode(connected = True)
cf.go_offline()
%matplotlib inline

In [96]:
df = pd.read_csv("SBIN-EQ.csv")
Price = df['Price'].tolist()
Date = df['Date'].tolist()

In [113]:

b = 7
start = b - 1
price = df.Price.tolist()
date = df.Date.tolist()
Price = np.asarray(price)
Date = np.asarray(date)
sma1 = talib.SMA(Price, timeperiod = b)
Trades = []
Dates =[]
Exit = []
for i in range(start, len(price)):
    i = start
    if i+1 == len(price):
        break
    else:
        if price[i] > sma1[i]:
            Trades.append(price[i])
            Dates.append(date[i])
            next = i + 1
            for i in range(next, len(price)):
                start = i
                if price[i] < sma1[i]:
                    Trades.append(price[i])
                    Dates.append(date[i])
                    Trades.append('B')
                    start = i
                    break
        if price[i] < sma1[i]:
            Trades.append(price[i])
            Dates.append(date[i])
            next = i + 1
            for i in range(next, len(price)):
                start = i
                if price[i] > sma1[i]:
                    Trades.append(price[i])
                    Dates.append(date[i])
                    Trades.append('S')
                    break
if len(Trades) % 3 ==1:
    Trades.pop(-1)
if len(Dates) % 2 ==1:
    Dates.pop(-1)
Entry = []
for i in range(0,len(Trades),3):
    Entry.append(Trades[i])
Exit = []
for i in range(1,len(Trades),3):
    Exit.append(Trades[i])
Signal = []
for i in range(2,len(Trades),3):
    Signal.append(Trades[i])
EntryDate = []
ExitDate   = []
for i in range(0,len(Dates),2):
    EntryDate.append(Dates[i])
for i in range(1,len(Dates),2):
    ExitDate.append(Dates[i])
PnL = []   
for i in range(len(Signal)):
    if Signal[i] == 'B':
        value = Exit[i] - Entry[i]
        PnL.append(value)
        
    else: 
        value = Entry[i] - Exit[i]
        PnL.append(value)
MA = pd.DataFrame(
    {'EntryDate': EntryDate,
     'Entry': Entry,
     'ExitDate': ExitDate,
     'Exit': Exit,
     'Signal': Signal,
     'PnL': PnL
    })

AttributeError: 'DataFrame' object has no attribute 'Price'

In [114]:
MA.PnL.sum()

43.69999999999999

In [99]:
MA

          EntryDate   Entry         ExitDate    Exit Signal    PnL
0     8/2/2019 9:15  314.05  7/31/2019 11:15  328.55      B  14.50
1   7/31/2019 11:15  328.55  7/30/2019 13:15  336.40      S  -7.85
2   7/30/2019 13:15  336.40  7/29/2019 12:15  343.20      B   6.80
3   7/29/2019 12:15  343.20  7/26/2019 15:15  342.80      S   0.40
4   7/26/2019 15:15  342.80   7/26/2019 9:15  343.05      B   0.25
5    7/26/2019 9:15  343.05   7/25/2019 9:15  340.90      S   2.15
6    7/25/2019 9:15  340.90  7/24/2019 14:15  339.00      B  -1.90
7   7/24/2019 14:15  339.00  7/24/2019 13:15  340.35      S  -1.35
8   7/24/2019 13:15  340.35  7/24/2019 12:15  338.25      B  -2.10
9   7/24/2019 12:15  338.25  7/24/2019 10:15  343.30      S  -5.05
10  7/24/2019 10:15  343.30  7/19/2019 10:15  356.15      B  12.85
11  7/19/2019 10:15  356.15   7/19/2019 9:15  358.50      S  -2.35
12   7/19/2019 9:15  358.50  7/17/2019 13:15  366.70      B   8.20
13  7/17/2019 13:15  366.70   7/16/2019 9:15  364.75      S   1.95
14   7/16/2019 9:15  364.75  7/15/2019 15:15  360.25      B  -4.50
15  7/15/2019 15:15  360.25  7/12/2019 15:15  363.30      S  -3.05
16  7/12/2019 15:15  363.30  7/12/2019 10:15  362.40      B  -0.90
17  7/12/2019 10:15  362.40  7/10/2019 10:15  356.50      S   5.90
18  7/10/2019 10:15  356.50   7/9/2019 11:15  358.30      B   1.80
19   7/9/2019 11:15  358.30   7/8/2019 11:15  356.80      S   1.50
20   7/8/2019 11:15  356.80   7/8/2019 10:15  355.35      B  -1.45
21   7/8/2019 10:15  355.35    7/8/2019 9:15  361.60      S  -6.25
22    7/8/2019 9:15  361.60    7/5/2019 9:15  368.70      B   7.10
23    7/5/2019 9:15  368.70   7/4/2019 13:15  369.50      S  -0.80
24   7/4/2019 13:15  369.50   7/3/2019 15:15  366.10      B  -3.40
25   7/3/2019 15:15  366.10   7/1/2019 10:15  361.15      S   4.95
26   7/1/2019 10:15  361.15    7/1/2019 9:15  359.70      B  -1.45
27    7/1/2019 9:15  359.70  6/28/2019 15:15  362.80      S  -3.10
28  6/28/2019 15:15  362.80  6/28/2019 14:15  359.80      B  -3.00
29  6/28/2019 14:15  359.80  6/28/2019 13:15  362.65      S  -2.85
..              ...     ...              ...     ...    ...    ...
66   5/9/2019 10:15  300.05   5/8/2019 15:15  298.45      B  -1.60
67   5/8/2019 15:15  298.45   5/8/2019 13:15  302.00      S  -3.55
68   5/8/2019 13:15  302.00   5/6/2019 15:15  308.60      B   6.60
69   5/6/2019 15:15  308.60   5/3/2019 15:15  309.70      S  -1.10
70   5/3/2019 15:15  309.70   5/3/2019 10:15  309.70      B   0.00
71   5/3/2019 10:15  309.70    5/3/2019 9:15  310.90      S  -1.20
72    5/3/2019 9:15  310.90   5/2/2019 15:15  307.90      B  -3.00
73   5/2/2019 15:15  307.90   5/2/2019 10:15  309.20      S  -1.30
74   5/2/2019 10:15  309.20  4/30/2019 13:15  307.50      B  -1.70
75  4/30/2019 13:15  307.50  4/26/2019 15:15  311.90      S  -4.40
76  4/26/2019 15:15  311.90  4/26/2019 12:15  308.60      B  -3.30
77  4/26/2019 12:15  308.60  4/25/2019 13:15  308.45      S   0.15
78  4/25/2019 13:15  308.45  4/24/2019 13:15  306.90      B  -1.55
79  4/24/2019 13:15  306.90  4/23/2019 13:15  310.85      S  -3.95
80  4/23/2019 13:15  310.85  4/22/2019 15:15  309.90      B  -0.95
81  4/22/2019 15:15  309.90  4/18/2019 15:15  310.20      S  -0.30
82  4/18/2019 15:15  310.20  4/18/2019 12:15  309.40      B  -0.80
83  4/18/2019 12:15  309.40  4/18/2019 11:15  310.15      S  -0.75
84  4/18/2019 11:15  310.15   4/18/2019 9:15  309.45      B  -0.70
85   4/18/2019 9:15  309.45  4/16/2019 15:15  315.65      S  -6.20
86  4/16/2019 15:15  315.65  4/15/2019 15:15  315.90      B   0.25
87  4/15/2019 15:15  315.90  4/15/2019 13:15  317.35      S  -1.45
88  4/15/2019 13:15  317.35  4/12/2019 15:15  314.50      B  -2.85
89  4/12/2019 15:15  314.50   4/12/2019 9:15  313.50      S   1.00
90   4/12/2019 9:15  313.50  4/11/2019 13:15  311.90      B  -1.60
91  4/11/2019 13:15  311.90  4/10/2019 14:15  310.95      S   0.95
92  4/10/2019 14:15  310.95   4/9/2019 12:15  312.00      B   1.05
93   4/9/2019 12:15  312.00   4/8/2019 15:15  312.75      S  -0.75
94   4/8/2019 15:15  312.75   4/5/2019 13:15  316.40      B   3.65
95   4/5/2019 13:15  316.40    4/5/2019 9:15  319.85      S  -3.45

[96 rows x 6 columns]

# SOMETHING NEW

In [100]:
list = MA['PnL'].tolist()
list

[14.5,
 -7.849999999999966,
 6.800000000000011,
 0.39999999999997726,
 0.25,
 2.150000000000034,
 -1.8999999999999773,
 -1.3500000000000227,
 -2.1000000000000227,
 -5.050000000000011,
 12.849999999999966,
 -2.3500000000000227,
 8.199999999999989,
 1.9499999999999886,
 -4.5,
 -3.0500000000000114,
 -0.9000000000000341,
 5.899999999999977,
 1.8000000000000114,
 1.5,
 -1.4499999999999886,
 -6.25,
 7.099999999999966,
 -0.8000000000000114,
 -3.3999999999999773,
 4.9500000000000455,
 -1.4499999999999886,
 -3.1000000000000227,
 -3.0,
 -2.849999999999966,
 -0.6499999999999773,
 4.600000000000023,
 -0.5499999999999545,
 3.8000000000000114,
 -1.900000000000034,
 11.049999999999955,
 -0.25,
 -2.25,
 -1.6000000000000227,
 -0.05000000000001137,
 2.25,
 -2.599999999999966,
 0.25,
 1.1499999999999773,
 -2.3999999999999773,
 1.3500000000000227,
 -4.449999999999989,
 -3.6999999999999886,
 12.949999999999989,
 -1.0,
 -2.6499999999999773,
 -1.599999999999966,
 4.900000000000034,
 -2.6499999999999773,
 -1.099999999999966,
 10.550000000000011,
 -6.300000000000011,
 5.550000000000011,
 4.800000000000011,
 25.44999999999999,
 -3.6000000000000227,
 0.5,
 1.8000000000000114,
 4.199999999999989,
 -3.0500000000000114,
 6.699999999999989,
 -1.6000000000000227,
 -3.5500000000000114,
 6.600000000000023,
 -1.099999999999966,
 0.0,
 -1.1999999999999886,
 -3.0,
 -1.3000000000000114,
 -1.6999999999999886,
 -4.399999999999977,
 -3.2999999999999545,
 0.1500000000000341,
 -1.5500000000000114,
 -3.9500000000000455,
 -0.9500000000000455,
 -0.30000000000001137,
 -0.8000000000000114,
 -0.75,
 -0.6999999999999886,
 -6.199999999999989,
 0.25,
 -1.4500000000000455,
 -2.8500000000000227,
 1.0,
 -1.6000000000000227,
 0.9499999999999886,
 1.0500000000000114,
 -0.75,
 3.6499999999999773,
 -3.4500000000000455]

In [101]:
new = list
for i in (w):
    new[i] = list[i]*-1
new

NameError: name 'w' is not defined

# Finding the growth

In [102]:
#x = MA.PnL
#real = x*20
#print(x.head())
#print(real.head())

In [92]:
lot = 45000
progress = []
growth = []
for i in range(len(real)):
    now = lot + real[i]
    lot = now
    progress.append(now)
growth = pd.DataFrame(progress)
growth.columns = ['y']
this = growth
this.min()

NameError: name 'real' is not defined

this['y'].min()

# BEST SMA

In [103]:
all = []
for i in range(2,5000):
    b =i
    start = b - 1
    price = df.Price.tolist()
    date = df.Date.tolist()
    Price = np.asarray(price)
    Date = np.asarray(date)
    sma1 = talib.SMA(Price, timeperiod = b)
    Trades = []
    Dates =[]
    Exit = []
    for i in range(start, len(price)):
        i = start
        if i+1 == len(price):
            break
        else:
            if price[i] > sma1[i]:
                Trades.append(price[i])
                Dates.append(date[i])
                next = i + 1
                for i in range(next, len(price)):
                    start = i
                    if price[i] < sma1[i]:
                        Trades.append(price[i])
                        Dates.append(date[i])
                        Trades.append('B')
                        start = i
                        break
            if price[i] < sma1[i]:
                Trades.append(price[i])
                Dates.append(date[i])
                next = i + 1
                for i in range(next, len(price)):
                    start = i
                    if price[i] > sma1[i]:
                        Trades.append(price[i])
                        Dates.append(date[i])
                        Trades.append('S')
                        break
    if len(Trades) % 3 ==1:
        Trades.pop(-1)
    if len(Dates) % 2 ==1:
        Dates.pop(-1)
    Entry = []
    for i in range(0,len(Trades),3):
        Entry.append(Trades[i])
    Exit = []
    for i in range(1,len(Trades),3):
        Exit.append(Trades[i])
    Signal = []
    for i in range(2,len(Trades),3):
        Signal.append(Trades[i])
    EntryDate = []
    ExitDate   = []
    for i in range(0,len(Dates),2):
        EntryDate.append(Dates[i])
    for i in range(1,len(Dates),2):
        ExitDate.append(Dates[i])
    PnL = []   
    for i in range(len(Signal)):
        if Signal[i] == 'B':
            value = Exit[i] - Entry[i]
            PnL.append(value)

        else: 
            value = Entry[i] - Exit[i]
            PnL.append(value)
    all.append(sum(PnL))

In [112]:

print(all.index(max(all)) + 2)
df = pd.DataFrame(all)
print(max(all))
print(all.index(min(all)) + 2)
print(min(all))

7
43.69999999999999
2
-91.65000000000015

In [106]:
df

          0
0    -91.65
1     11.75
2     25.85
3     33.90
4     12.80
5     43.70
6     31.25
7     40.05
8     23.50
9     -4.75
10   -27.95
11   -32.55
12   -20.45
13   -13.65
14   -26.00
15   -24.70
16   -29.45
17   -23.40
18   -17.10
19   -25.05
20    -7.60
21    -8.80
22   -20.25
23   -16.80
24   -18.40
25    -9.05
26   -23.80
27   -20.85
28   -39.10
29   -39.65
...     ...
4968   0.00
4969   0.00
4970   0.00
4971   0.00
4972   0.00
4973   0.00
4974   0.00
4975   0.00
4976   0.00
4977   0.00
4978   0.00
4979   0.00
4980   0.00
4981   0.00
4982   0.00
4983   0.00
4984   0.00
4985   0.00
4986   0.00
4987   0.00
4988   0.00
4989   0.00
4990   0.00
4991   0.00
4992   0.00
4993   0.00
4994   0.00
4995   0.00
4996   0.00
4997   0.00

[4998 rows x 1 columns]

In [31]:
x = -2
x*-1

2

In [32]:
trace0= go.Scatter(
        x= df['Price'],
        y= df['Volume'])

NameError: name 'go' is not defined